/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:ec810eb2-f28f-4820-926e-d74db8469a1e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_cEzC0tWe3",
    "aws_user_pools_web_client_id": "7d3jnhtq79et18h017ut2715bs",
    "oauth": {}
};


export default awsmobile;
