/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:ec810eb2-f28f-4820-926e-d74db8469a1e",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_cEzC0tWe3",
    "aws_user_pools_web_client_id": "7d3jnhtq79et18h017ut2715bs",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pbuskigpwngaffv5enl2wvcmby.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-labyqfkvnjfo5aw7kc5k7wjyhu",
    "aws_user_files_s3_bucket": "todosapp70643dea6cae4c27998f5b79aa64ac0a91426-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
